import "./globals.css";
import Navbar from "../components/navbar/index";
import Footer from "../components/footer/index";
// import "@mantine/core/styles.css";
import { MantineProvider } from "@mantine/core";
import "@mantine/carousel/styles.css";

import { josefin_slab, roboto_mono, cormorant} from "./ui/font";

export const metadata = {
  title: "PT. Dapoer Poesat Noesantara Group",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={cormorant.className}>
        <MantineProvider>
          <Navbar />
          {children}
          <Footer />
        </MantineProvider>
      </body>
    </html>
  );
}
